### ISSUE TITLE
[QUESTION] Using this for PL

### ISSUE THREAD

**Issue by kokonut27** [thesephist/oak-syntax-visualizer#1]
So I had a quick question;

Would it be possible if/and I could use this to implement into a lang I'm coding?

##### The 'if' being is it possible, and the 'and' being if it's possible, with your permission, could I implement this into my lang?

Thanks!

**Comment by kokonut27** [comment]
Whoops, I just realized that this was made for *your* specific language lol.

But still, other than that, would it be okay if I "stole" some code, and then implemented it into mine? I would obviously credit you, but if you don't want that, it's okay :)

**Comment by thesephist** [comment]
Please feel free to take the ideas and/or implementation! If you take any code _verbatim_, I would ask that you stick to the terms of the MIT License, but considering it's written in my language I add that only just in case :)

**Comment by thesephist** [comment]
Note that most of the parser/tokenizer is actually in:

- Oak's standard library (https://github.com/thesephist/oak/blob/main/lib/syntax.oak) implemented in Oak, or
- The Oak tokenizer/parser (https://github.com/thesephist/oak) written in Go

They're under the same license, so what I said above also apply. But yeah, the code in this repo is a UI wrapper around the actual tokenizer/parser in those other places to help visualize stuff for my talk.

**Comment by kokonut27** [comment]
Okay, thanks for the response!
